name: Bug Report
description: Create a report to help us improve CHIMERA
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us resolve the issue quickly.

        **Security Notice:** If this involves a security vulnerability, please use our [security disclosure process](https://github.com/lucien-vallois/adversarial-phish-forge/blob/master/SECURITY.md) instead.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief description of the bug
      placeholder: "e.g., Kill switch doesn't activate when consent is revoked"
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How critical is this bug?
      options:
        - Critical - System unusable or security risk
        - High - Major functionality broken
        - Medium - Feature partially broken
        - Low - Minor issue or enhancement
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of CHIMERA is affected?
      options:
        - Core Engine (orchestrator)
        - Consent System
        - Kill Switch
        - Rate Limiting
        - Privacy Filter
        - Pretext Engine
        - Identity Graph
        - Email Delivery
        - Tracking Server
        - CLI Interface
        - Docker Infrastructure
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Detailed description of the bug
      placeholder: |
        ## Steps to Reproduce
        1. Go to '...'
        2. Click on '...'
        3. See error

        ## Expected Behavior
        What should happen?

        ## Actual Behavior
        What actually happens?

        ## Environment
        - OS: [e.g., Ubuntu 22.04]
        - Python Version: [e.g., 3.11.0]
        - CHIMERA Version: [e.g., 1.0.0]
        - Docker Version: [if applicable]
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Start CHIMERA in safe mode
        2. Create a campaign with 5 recipients
        3. Attempt to send emails
        4. Observe error in logs
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen when the steps above are followed?
      placeholder: "Emails should be sent successfully with consent verification"
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "System throws consent verification error despite valid consent"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information and configuration
      value: |
        - **OS**: [e.g., Windows 11, Ubuntu 22.04, macOS 13]
        - **Python Version**: [e.g., 3.11.0]
        - **CHIMERA Version**: [e.g., 1.0.0]
        - **Docker Version**: [if applicable, e.g., 24.0.2]
        - **Database**: [PostgreSQL, Redis versions]
        - **Deployment**: [Local, Docker Compose, Kubernetes]
        - **Configuration**: [Safe Mode, Custom config]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Error Messages
      description: Relevant log output or error messages
      placeholder: |
        ```
        2025-12-19 10:30:00 ERROR Consent verification failed for participant abc123
        2025-12-19 10:30:01 ERROR Kill switch activation timeout
        ```
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: |
        - Screenshots
        - Configuration files (redact sensitive data)
        - Related issues or PRs
        - Performance impact
        - Security implications

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm these items
      options:
        - label: I have checked that this issue hasn't been reported before
          required: true
        - label: I have provided all required information
          required: true
        - label: I have redacted any sensitive information from logs/config
          required: true
        - label: This issue does not involve security vulnerabilities
          required: true
        - label: I am willing to help test proposed fixes
          required: false
