name: Feature Request
description: Suggest an idea for CHIMERA
title: "[FEATURE] "
labels: ["enhancement", "feature-request"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Your input helps make CHIMERA better for the security research community.

        **Important:** All features must align with CHIMERA's ethical use requirements and legal compliance standards.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the proposed feature
      placeholder: "e.g., Add support for multi-language email templates"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Nice to have - Future consideration
        - Should have - Important for completeness
        - Must have - Critical for security/ethics/compliance
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which CHIMERA component would this affect?
      options:
        - Core Engine (orchestrator)
        - Consent System
        - Kill Switch
        - Rate Limiting
        - Privacy Filter
        - Pretext Engine
        - Identity Graph
        - Email Delivery
        - Tracking Server
        - CLI Interface
        - Docker Infrastructure
        - Documentation
        - Monitoring & Analytics
        - Testing Infrastructure
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What's the problem this feature would solve?
      placeholder: |
        ## Current Situation
        Currently, CHIMERA only supports English email templates...

        ## Pain Points
        - International teams cannot use localized content
        - Cultural context is lost in translations
        - Compliance requirements vary by jurisdiction
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
      placeholder: |
        ## Implementation Approach
        1. Add i18n support to pretext engine
        2. Create template translation system
        3. Add cultural context validation

        ## API Changes
        - New endpoint: `POST /api/v1/templates/{lang}`
        - Configuration option: `pretext_engine.languages`

        ## User Experience
        - Language selection in campaign creation
        - Automatic cultural adaptation
        - Compliance checking per jurisdiction
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: |
        ## Considered Alternatives
        1. **External Translation Services**: Using Google Translate API
           - Pros: Quick implementation
           - Cons: Privacy concerns, quality issues

        2. **Manual Template Creation**: Allow users to create localized templates
           - Pros: High quality control
           - Cons: Time-consuming, scalability issues

        ## Why This Approach?
        Integrated solution provides better quality control and maintains privacy.
    validations:
      required: false

  - type: textarea
    id: security_considerations
    attributes:
      label: Security & Ethical Considerations
      description: How does this feature impact security and ethical use?
      placeholder: |
        ## Security Impact
        - **Data Privacy**: No additional PII collection
        - **Access Control**: Inherits existing RBAC
        - **Audit Trail**: All template changes logged

        ## Ethical Considerations
        - **Cultural Sensitivity**: Templates must respect local customs
        - **Consent Requirements**: No changes to consent framework
        - **Misuse Prevention**: Content validation prevents harmful messaging

        ## Legal Compliance
        - **GDPR**: No additional data processing
        - **CFAA**: Maintains authorized use restrictions
        - **International Law**: Must comply with local regulations
    validations:
      required: true

  - type: textarea
    id: implementation_notes
    attributes:
      label: Implementation Notes
      description: Technical details and considerations
      placeholder: |
        ## Technical Requirements
        - Python i18n libraries (gettext, babel)
        - Template validation system
        - Database schema changes for multi-language support

        ## Testing Requirements
        - Unit tests for translation logic
        - Integration tests for template rendering
        - Cultural validation testing

        ## Performance Impact
        - Minimal impact on email generation
        - Additional storage for translated templates
        - Caching strategy for frequently used languages

        ## Backward Compatibility
        - Existing English templates continue to work
        - No breaking changes to API
        - Gradual rollout possible
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this feature is complete?
      placeholder: |
        ## Functional Requirements
        - [ ] Support for 10+ languages
        - [ ] Template translation workflow
        - [ ] Cultural context validation
        - [ ] API endpoints for language management

        ## Quality Requirements
        - [ ] 80%+ test coverage
        - [ ] Documentation updated
        - [ ] Performance benchmarks met
        - [ ] Security review completed

        ## Compliance Requirements
        - [ ] Ethical use guidelines followed
        - [ ] Legal review completed
        - [ ] Privacy impact assessment done
    validations:
      required: true

  - type: dropdown
    id: effort_estimate
    attributes:
      label: Effort Estimate
      description: Rough estimate of implementation effort
      options:
        - Small (1-2 days)
        - Medium (1-2 weeks)
        - Large (1-2 months)
        - X-Large (2-6 months)
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: |
        - Related research papers
        - Similar features in other tools
        - Community requests
        - Business justification
        - Screenshots/mockups

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm these items
      options:
        - label: This feature aligns with CHIMERA's ethical use requirements
          required: true
        - label: I have considered security and privacy implications
          required: true
        - label: This feature would benefit the security research community
          required: true
        - label: I am willing to help implement or test this feature
          required: false
